### ISSUE TITLE
env = gym.make('CartPole-v0')报错

### ISSUE THREAD

**Issue by kepma** [PacktPublishing/Hands-On-Reinforcement-Learning-with-Python#3]
PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)

**Comment by sujitpal** [comment]
This looks like an issue with gym (see issue https://github.com/openai/gym/issues/1219). Fix has been submitted per (PR https://github.com/openai/gym/pull/942) but not yet merged. Once it is merged, `pip install --upgrade gym` should fix the deprecation warning. Meanwhile since it is not an error, it should be okay to ignore.
